### ISSUE TITLE
nextjs styled ripple not working

### ISSUE THREAD

**Issue by nicolasGallegos** [primefaces/primereact-examples#18]
Clone the repository and modify the _app.js file, add things to the value of the "PrimeReactProvider", 
export default function App({ Component, pageProps }) {
  return (
    <PrimeReactProvider
      value={{
        unstyled: false,
        pt: Tailwind,
        ripple: false,
        inputStyle: "filled",
      }}
    >
      <Component {...pageProps} />
    </PrimeReactProvider>
  );
}

**Comment by melloware** [comment]
@buraksaglam089 want to look at this one?
