### ISSUE TITLE
vite-unstyled-tailwind - Accordion

### ISSUE THREAD

**Issue by areski** [primefaces/primereact-examples#29]
In the `[vite-unstyled-tailwind](https://github.com/primefaces/primereact-examples/tree/main/vite-unstyled-tailwind)` if we add an accordion, we obtain an accordion that has a very different behavior than the original.

See attached screen here:
![Peek 2024-03-21 13-38](https://github.com/primefaces/primereact-examples/assets/53455/7daa88ab-a7c5-4da0-8bfb-004fdb95553d)

As you can see, it opens and then close, rather than having a smooth transition:
https://primereact.org/accordion/

**Comment by melloware** [comment]
See this ticket someone just fixed the tailwind animations: https://github.com/primefaces/primereact/issues/5540

**Comment by melloware** [comment]
@areski are you using PrimeReact 10.5.3 ?

**Comment by areski** [comment]
@melloware yes, that was tested with v10.5.3

**Comment by melloware** [comment]
OK I asked @Tarik1700 to chime in...he made the Tailwind animation changes.

**Comment by Tarik1700** [comment]
@melloware This seems like a different issue, my guess is that the tailwind version uses 1 timeout to control both the exit and enter animations, where as the regular accordion uses a dual timeout as i can see in the code. Just a guess tho, i'll take a look if i find the time for it.
<img width="425" alt="image" src="https://github.com/primefaces/primereact-examples/assets/71398993/708fd75d-e6ad-495e-a471-0e7b66e62494">

**Comment by melloware** [comment]
OK I closed this as he opened a ticket on the real PrimeReact Issue page where it belongs.
