### ISSUE TITLE
remix-run-basic - 404

### ISSUE THREAD

**Issue by daniel-kehlibarov** [primefaces/primereact-examples#32]
Hi, was there a `remix-run-basic` example once?
It's giving me a 404. :)

Thanks!

![image](https://github.com/primefaces/primereact-examples/assets/125644289/c6e80732-7286-4d35-91bc-7cd3221d730d)

Redirected from:
https://primereact.org/installation/#examples
![image](https://github.com/primefaces/primereact-examples/assets/125644289/ad7f8df9-a6c4-4333-8001-e3ef2625ccf7)

**Comment by melloware** [comment]
There was a remix run example but Remix does not work well with PrimeReact.  There were a bunch of open Remix tickets about it so we removed the old example.

**Comment by daniel-kehlibarov** [comment]
Got it, thanks!
