### ISSUE TITLE
TS Complied Problem

### ISSUE THREAD

**Issue by selimsezr** [primefaces/primereact-examples#5]
`<InputTextarea id="description" value={product.description} onChange={(e) => onDescriptionChange(e)} required rows={3} cols={20} />`
Property 'rows' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<InputTextarea> & Readonly<InputTextareaProps>'.
I tried a lot but the result is the same.

**Comment by melloware** [comment]
Already been reported against 8.5.0 and fixed in upcoming 8.6.0: https://github.com/primefaces/primereact/issues/3252

For now just downgrade to PR 8.4.0
